### ISSUE TITLE
example with tmpfs doesn't work

### ISSUE THREAD

**Issue by GentleHedgehog** [gitblit/gitblit-docker#12]
Try to use (from https://github.com/gitblit/gitblit-docker/blob/master/hub-readme.md): 
`docker run --rm -d --name gitblit --tmpfs /var/opt/gitblit/temp -p 8443:8443 gitblit/gitblit`

But result is (https://localhost:8443/): 
```
HTTP ERROR: 503
Problem accessing /. Reason:
    Service Unavailable
```
Without tmpfs - that is OK:
`docker run --rm -d --name gitblit -p 8443:8443 gitblit/gitblit`

**Comment by flaix** [comment]
```
2021-04-16 08:07:38 [INFO ] Running on Linux (4.19.76-linuxkit)
2021-04-16 08:07:38 [INFO ] JVM version 1.8.0_242 (Oracle Corporation)
2021-04-16 08:07:38 [INFO ] Logging initialized @600ms
...
2021-04-16 08:07:39 [INFO ] Setting up HTTP transport on port 8080
2021-04-16 08:07:40 [WARN ] Failed to delete temp dir /var/opt/gitblit/temp
java.io.IOException: Could not delete file /var/opt/gitblit/temp
	at org.eclipse.jgit.util.FileUtils.delete(FileUtils.java:197)
	at com.gitblit.GitBlitServer.start(GitBlitServer.java:357)
	at com.gitblit.GitBlitServer.main(GitBlitServer.java:124)
2021-04-16 08:07:40 [WARN ] Failed to create temp dir /var/opt/gitblit/temp
```
